set_property SRC_FILE_INFO {cfile:e:/XilinxPrj/AXU5EVB/2020/course_s1_fpga/10_pl_ddr4_test/pl_ddr4.srcs/sources_1/ip/ddr4/ddr4/ddr4_in_context.xdc rfile:../../../pl_ddr4.srcs/sources_1/ip/ddr4/ddr4/ddr4_in_context.xdc id:1 order:EARLY scoped_inst:u_ddr4} [current_design]
set_property SRC_FILE_INFO {cfile:E:/XilinxPrj/AXU5EVB/2020/course_s1_fpga/10_pl_ddr4_test/pl_ddr4.srcs/constrs_1/new/ddr4_set.xdc rfile:../../../pl_ddr4.srcs/constrs_1/new/ddr4_set.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:E:/XilinxPrj/AXU5EVB/2020/course_s1_fpga/10_pl_ddr4_test/pl_ddr4.srcs/constrs_1/new/system.xdc rfile:../../../pl_ddr4.srcs/constrs_1/new/system.xdc id:3} [current_design]
current_instance u_ddr4
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.003 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports c0_sys_clk_p] -edges {1 2 3} -edge_shift {0.000 -0.625 -1.251} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports c0_sys_clk_p] -edges {1 2 3} -edge_shift {0.000 5.003 10.006} [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH4 [get_ports {c0_ddr4_odt[0]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE8 [get_ports {c0_ddr4_bg[0]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports {c0_ddr4_adr[16]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports {c0_ddr4_adr[15]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF6 [get_ports {c0_ddr4_adr[14]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD9 [get_ports {c0_ddr4_adr[13]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC6 [get_ports {c0_ddr4_adr[12]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH9 [get_ports {c0_ddr4_adr[11]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE7 [get_ports {c0_ddr4_adr[10]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports {c0_ddr4_adr[9]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8 [get_ports {c0_ddr4_adr[8]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE9 [get_ports {c0_ddr4_adr[7]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH7 [get_ports {c0_ddr4_adr[6]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD7 [get_ports {c0_ddr4_adr[5]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF7 [get_ports {c0_ddr4_adr[4]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8 [get_ports {c0_ddr4_adr[3]}]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8 [get_ports {c0_ddr4_adr[2]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports {c0_ddr4_adr[1]}]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG8 [get_ports {c0_ddr4_adr[0]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD2 [get_ports {c0_ddr4_dqs_t[1]}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1 [get_ports {c0_ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2 [get_ports {c0_ddr4_dqs_t[0]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2 [get_ports {c0_ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4 [get_ports {c0_ddr4_dq[15]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC3 [get_ports {c0_ddr4_dq[14]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4 [get_ports {c0_ddr4_dq[13]}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB3 [get_ports {c0_ddr4_dq[12]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2 [get_ports {c0_ddr4_dq[11]}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2 [get_ports {c0_ddr4_dq[10]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1 [get_ports {c0_ddr4_dq[9]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1 [get_ports {c0_ddr4_dq[8]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG3 [get_ports {c0_ddr4_dq[7]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH3 [get_ports {c0_ddr4_dq[6]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3 [get_ports {c0_ddr4_dq[5]}]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3 [get_ports {c0_ddr4_dq[4]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH2 [get_ports {c0_ddr4_dq[3]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH1 [get_ports {c0_ddr4_dq[2]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF1 [get_ports {c0_ddr4_dq[1]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG1 [get_ports {c0_ddr4_dq[0]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports {c0_ddr4_cs_n[0]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG6 [get_ports {c0_ddr4_ck_t[0]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG5 [get_ports {c0_ddr4_ck_c[0]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE4 [get_ports {c0_ddr4_cke[0]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG9 [get_ports c0_ddr4_reset_n]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD4 [get_ports c0_ddr4_act_n]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7 [get_ports {c0_ddr4_ba[1]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH6 [get_ports {c0_ddr4_ba[0]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD5 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG4 [get_ports {c0_ddr4_dm_dbi_n[0]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5 [get_ports c0_sys_clk_p]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5 [get_ports c0_sys_clk_n]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list mem_burst_m0/app_wdf_wren]]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_ddr4/inst/u_ddr4_infrastructure/input_rst_mmcm_reg_0]]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {mem_burst_m0/rd_addr_cnt[0]} {mem_burst_m0/rd_addr_cnt[1]} {mem_burst_m0/rd_addr_cnt[2]} {mem_burst_m0/rd_addr_cnt[3]} {mem_burst_m0/rd_addr_cnt[4]} {mem_burst_m0/rd_addr_cnt[5]} {mem_burst_m0/rd_addr_cnt[6]} {mem_burst_m0/rd_addr_cnt[7]} {mem_burst_m0/rd_addr_cnt[8]} {mem_burst_m0/rd_addr_cnt[9]}]]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {mem_burst_m0/rd_data_cnt[0]} {mem_burst_m0/rd_data_cnt[1]} {mem_burst_m0/rd_data_cnt[2]} {mem_burst_m0/rd_data_cnt[3]} {mem_burst_m0/rd_data_cnt[4]} {mem_burst_m0/rd_data_cnt[5]} {mem_burst_m0/rd_data_cnt[6]} {mem_burst_m0/rd_data_cnt[7]} {mem_burst_m0/rd_data_cnt[8]} {mem_burst_m0/rd_data_cnt[9]}]]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {mem_test_m0/rd_burst_len[0]} {mem_test_m0/rd_burst_len[1]} {mem_test_m0/rd_burst_len[2]} {mem_test_m0/rd_burst_len[3]} {mem_test_m0/rd_burst_len[4]} {mem_test_m0/rd_burst_len[5]} {mem_test_m0/rd_burst_len[6]} {mem_test_m0/rd_burst_len[7]} {mem_test_m0/rd_burst_len[8]} {mem_test_m0/rd_burst_len[9]}]]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {mem_burst_m0/state[0]} {mem_burst_m0/state[1]} {mem_burst_m0/state[2]}]]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {mem_burst_m0/wr_addr_cnt[0]} {mem_burst_m0/wr_addr_cnt[1]} {mem_burst_m0/wr_addr_cnt[2]} {mem_burst_m0/wr_addr_cnt[3]} {mem_burst_m0/wr_addr_cnt[4]} {mem_burst_m0/wr_addr_cnt[5]} {mem_burst_m0/wr_addr_cnt[6]} {mem_burst_m0/wr_addr_cnt[7]} {mem_burst_m0/wr_addr_cnt[8]} {mem_burst_m0/wr_addr_cnt[9]}]]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 28 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {mem_burst_m0/app_addr[0]} {mem_burst_m0/app_addr[1]} {mem_burst_m0/app_addr[2]} {mem_burst_m0/app_addr[3]} {mem_burst_m0/app_addr[4]} {mem_burst_m0/app_addr[5]} {mem_burst_m0/app_addr[6]} {mem_burst_m0/app_addr[7]} {mem_burst_m0/app_addr[8]} {mem_burst_m0/app_addr[9]} {mem_burst_m0/app_addr[10]} {mem_burst_m0/app_addr[11]} {mem_burst_m0/app_addr[12]} {mem_burst_m0/app_addr[13]} {mem_burst_m0/app_addr[14]} {mem_burst_m0/app_addr[15]} {mem_burst_m0/app_addr[16]} {mem_burst_m0/app_addr[17]} {mem_burst_m0/app_addr[18]} {mem_burst_m0/app_addr[19]} {mem_burst_m0/app_addr[20]} {mem_burst_m0/app_addr[21]} {mem_burst_m0/app_addr[22]} {mem_burst_m0/app_addr[23]} {mem_burst_m0/app_addr[24]} {mem_burst_m0/app_addr[25]} {mem_burst_m0/app_addr[26]} {mem_burst_m0/app_addr[27]}]]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {mem_burst_m0/wr_data_cnt[0]} {mem_burst_m0/wr_data_cnt[1]} {mem_burst_m0/wr_data_cnt[2]} {mem_burst_m0/wr_data_cnt[3]} {mem_burst_m0/wr_data_cnt[4]} {mem_burst_m0/wr_data_cnt[5]} {mem_burst_m0/wr_data_cnt[6]} {mem_burst_m0/wr_data_cnt[7]} {mem_burst_m0/wr_data_cnt[8]} {mem_burst_m0/wr_data_cnt[9]}]]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {mem_burst_m0/app_cmd[0]} {mem_burst_m0/app_cmd[1]} {mem_burst_m0/app_cmd[2]}]]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {mem_test_m0/test_cnt[0]} {mem_test_m0/test_cnt[1]} {mem_test_m0/test_cnt[2]} {mem_test_m0/test_cnt[3]} {mem_test_m0/test_cnt[4]} {mem_test_m0/test_cnt[5]} {mem_test_m0/test_cnt[6]} {mem_test_m0/test_cnt[7]} {mem_test_m0/test_cnt[8]} {mem_test_m0/test_cnt[9]} {mem_test_m0/test_cnt[10]} {mem_test_m0/test_cnt[11]} {mem_test_m0/test_cnt[12]} {mem_test_m0/test_cnt[13]} {mem_test_m0/test_cnt[14]} {mem_test_m0/test_cnt[15]}]]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 128 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {mem_test_m0/rd_burst_data[0]} {mem_test_m0/rd_burst_data[1]} {mem_test_m0/rd_burst_data[2]} {mem_test_m0/rd_burst_data[3]} {mem_test_m0/rd_burst_data[4]} {mem_test_m0/rd_burst_data[5]} {mem_test_m0/rd_burst_data[6]} {mem_test_m0/rd_burst_data[7]} {mem_test_m0/rd_burst_data[8]} {mem_test_m0/rd_burst_data[9]} {mem_test_m0/rd_burst_data[10]} {mem_test_m0/rd_burst_data[11]} {mem_test_m0/rd_burst_data[12]} {mem_test_m0/rd_burst_data[13]} {mem_test_m0/rd_burst_data[14]} {mem_test_m0/rd_burst_data[15]} {mem_test_m0/rd_burst_data[16]} {mem_test_m0/rd_burst_data[17]} {mem_test_m0/rd_burst_data[18]} {mem_test_m0/rd_burst_data[19]} {mem_test_m0/rd_burst_data[20]} {mem_test_m0/rd_burst_data[21]} {mem_test_m0/rd_burst_data[22]} {mem_test_m0/rd_burst_data[23]} {mem_test_m0/rd_burst_data[24]} {mem_test_m0/rd_burst_data[25]} {mem_test_m0/rd_burst_data[26]} {mem_test_m0/rd_burst_data[27]} {mem_test_m0/rd_burst_data[28]} {mem_test_m0/rd_burst_data[29]} {mem_test_m0/rd_burst_data[30]} {mem_test_m0/rd_burst_data[31]} {mem_test_m0/rd_burst_data[32]} {mem_test_m0/rd_burst_data[33]} {mem_test_m0/rd_burst_data[34]} {mem_test_m0/rd_burst_data[35]} {mem_test_m0/rd_burst_data[36]} {mem_test_m0/rd_burst_data[37]} {mem_test_m0/rd_burst_data[38]} {mem_test_m0/rd_burst_data[39]} {mem_test_m0/rd_burst_data[40]} {mem_test_m0/rd_burst_data[41]} {mem_test_m0/rd_burst_data[42]} {mem_test_m0/rd_burst_data[43]} {mem_test_m0/rd_burst_data[44]} {mem_test_m0/rd_burst_data[45]} {mem_test_m0/rd_burst_data[46]} {mem_test_m0/rd_burst_data[47]} {mem_test_m0/rd_burst_data[48]} {mem_test_m0/rd_burst_data[49]} {mem_test_m0/rd_burst_data[50]} {mem_test_m0/rd_burst_data[51]} {mem_test_m0/rd_burst_data[52]} {mem_test_m0/rd_burst_data[53]} {mem_test_m0/rd_burst_data[54]} {mem_test_m0/rd_burst_data[55]} {mem_test_m0/rd_burst_data[56]} {mem_test_m0/rd_burst_data[57]} {mem_test_m0/rd_burst_data[58]} {mem_test_m0/rd_burst_data[59]} {mem_test_m0/rd_burst_data[60]} {mem_test_m0/rd_burst_data[61]} {mem_test_m0/rd_burst_data[62]} {mem_test_m0/rd_burst_data[63]} {mem_test_m0/rd_burst_data[64]} {mem_test_m0/rd_burst_data[65]} {mem_test_m0/rd_burst_data[66]} {mem_test_m0/rd_burst_data[67]} {mem_test_m0/rd_burst_data[68]} {mem_test_m0/rd_burst_data[69]} {mem_test_m0/rd_burst_data[70]} {mem_test_m0/rd_burst_data[71]} {mem_test_m0/rd_burst_data[72]} {mem_test_m0/rd_burst_data[73]} {mem_test_m0/rd_burst_data[74]} {mem_test_m0/rd_burst_data[75]} {mem_test_m0/rd_burst_data[76]} {mem_test_m0/rd_burst_data[77]} {mem_test_m0/rd_burst_data[78]} {mem_test_m0/rd_burst_data[79]} {mem_test_m0/rd_burst_data[80]} {mem_test_m0/rd_burst_data[81]} {mem_test_m0/rd_burst_data[82]} {mem_test_m0/rd_burst_data[83]} {mem_test_m0/rd_burst_data[84]} {mem_test_m0/rd_burst_data[85]} {mem_test_m0/rd_burst_data[86]} {mem_test_m0/rd_burst_data[87]} {mem_test_m0/rd_burst_data[88]} {mem_test_m0/rd_burst_data[89]} {mem_test_m0/rd_burst_data[90]} {mem_test_m0/rd_burst_data[91]} {mem_test_m0/rd_burst_data[92]} {mem_test_m0/rd_burst_data[93]} {mem_test_m0/rd_burst_data[94]} {mem_test_m0/rd_burst_data[95]} {mem_test_m0/rd_burst_data[96]} {mem_test_m0/rd_burst_data[97]} {mem_test_m0/rd_burst_data[98]} {mem_test_m0/rd_burst_data[99]} {mem_test_m0/rd_burst_data[100]} {mem_test_m0/rd_burst_data[101]} {mem_test_m0/rd_burst_data[102]} {mem_test_m0/rd_burst_data[103]} {mem_test_m0/rd_burst_data[104]} {mem_test_m0/rd_burst_data[105]} {mem_test_m0/rd_burst_data[106]} {mem_test_m0/rd_burst_data[107]} {mem_test_m0/rd_burst_data[108]} {mem_test_m0/rd_burst_data[109]} {mem_test_m0/rd_burst_data[110]} {mem_test_m0/rd_burst_data[111]} {mem_test_m0/rd_burst_data[112]} {mem_test_m0/rd_burst_data[113]} {mem_test_m0/rd_burst_data[114]} {mem_test_m0/rd_burst_data[115]} {mem_test_m0/rd_burst_data[116]} {mem_test_m0/rd_burst_data[117]} {mem_test_m0/rd_burst_data[118]} {mem_test_m0/rd_burst_data[119]} {mem_test_m0/rd_burst_data[120]} {mem_test_m0/rd_burst_data[121]} {mem_test_m0/rd_burst_data[122]} {mem_test_m0/rd_burst_data[123]} {mem_test_m0/rd_burst_data[124]} {mem_test_m0/rd_burst_data[125]} {mem_test_m0/rd_burst_data[126]} {mem_test_m0/rd_burst_data[127]}]]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {mem_test_m0/rd_cnt[0]} {mem_test_m0/rd_cnt[1]} {mem_test_m0/rd_cnt[2]} {mem_test_m0/rd_cnt[3]} {mem_test_m0/rd_cnt[4]} {mem_test_m0/rd_cnt[5]} {mem_test_m0/rd_cnt[6]} {mem_test_m0/rd_cnt[7]} {mem_test_m0/rd_cnt[8]} {mem_test_m0/rd_cnt[9]}]]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {mem_test_m0/state[0]} {mem_test_m0/state[1]} {mem_test_m0/state[2]}]]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {mem_test_m0/wr_cnt[0]} {mem_test_m0/wr_cnt[1]} {mem_test_m0/wr_cnt[2]} {mem_test_m0/wr_cnt[3]} {mem_test_m0/wr_cnt[4]} {mem_test_m0/wr_cnt[5]} {mem_test_m0/wr_cnt[6]} {mem_test_m0/wr_cnt[7]} {mem_test_m0/wr_cnt[8]} {mem_test_m0/wr_cnt[9]}]]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 28 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {mem_test_m0/rd_burst_addr[0]} {mem_test_m0/rd_burst_addr[1]} {mem_test_m0/rd_burst_addr[2]} {mem_test_m0/rd_burst_addr[3]} {mem_test_m0/rd_burst_addr[4]} {mem_test_m0/rd_burst_addr[5]} {mem_test_m0/rd_burst_addr[6]} {mem_test_m0/rd_burst_addr[7]} {mem_test_m0/rd_burst_addr[8]} {mem_test_m0/rd_burst_addr[9]} {mem_test_m0/rd_burst_addr[10]} {mem_test_m0/rd_burst_addr[11]} {mem_test_m0/rd_burst_addr[12]} {mem_test_m0/rd_burst_addr[13]} {mem_test_m0/rd_burst_addr[14]} {mem_test_m0/rd_burst_addr[15]} {mem_test_m0/rd_burst_addr[16]} {mem_test_m0/rd_burst_addr[17]} {mem_test_m0/rd_burst_addr[18]} {mem_test_m0/rd_burst_addr[19]} {mem_test_m0/rd_burst_addr[20]} {mem_test_m0/rd_burst_addr[21]} {mem_test_m0/rd_burst_addr[22]} {mem_test_m0/rd_burst_addr[23]} {mem_test_m0/rd_burst_addr[24]} {mem_test_m0/rd_burst_addr[25]} {mem_test_m0/rd_burst_addr[26]} {mem_test_m0/rd_burst_addr[27]}]]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {mem_test_m0/rd_data_pre_add[0]} {mem_test_m0/rd_data_pre_add[1]} {mem_test_m0/rd_data_pre_add[2]} {mem_test_m0/rd_data_pre_add[3]} {mem_test_m0/rd_data_pre_add[4]} {mem_test_m0/rd_data_pre_add[5]} {mem_test_m0/rd_data_pre_add[6]} {mem_test_m0/rd_data_pre_add[7]} {mem_test_m0/rd_data_pre_add[8]} {mem_test_m0/rd_data_pre_add[9]} {mem_test_m0/rd_data_pre_add[10]} {mem_test_m0/rd_data_pre_add[11]} {mem_test_m0/rd_data_pre_add[12]} {mem_test_m0/rd_data_pre_add[13]} {mem_test_m0/rd_data_pre_add[14]} {mem_test_m0/rd_data_pre_add[15]}]]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 128 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {mem_test_m0/wr_burst_data[0]} {mem_test_m0/wr_burst_data[1]} {mem_test_m0/wr_burst_data[2]} {mem_test_m0/wr_burst_data[3]} {mem_test_m0/wr_burst_data[4]} {mem_test_m0/wr_burst_data[5]} {mem_test_m0/wr_burst_data[6]} {mem_test_m0/wr_burst_data[7]} {mem_test_m0/wr_burst_data[8]} {mem_test_m0/wr_burst_data[9]} {mem_test_m0/wr_burst_data[10]} {mem_test_m0/wr_burst_data[11]} {mem_test_m0/wr_burst_data[12]} {mem_test_m0/wr_burst_data[13]} {mem_test_m0/wr_burst_data[14]} {mem_test_m0/wr_burst_data[15]} {mem_test_m0/wr_burst_data[16]} {mem_test_m0/wr_burst_data[17]} {mem_test_m0/wr_burst_data[18]} {mem_test_m0/wr_burst_data[19]} {mem_test_m0/wr_burst_data[20]} {mem_test_m0/wr_burst_data[21]} {mem_test_m0/wr_burst_data[22]} {mem_test_m0/wr_burst_data[23]} {mem_test_m0/wr_burst_data[24]} {mem_test_m0/wr_burst_data[25]} {mem_test_m0/wr_burst_data[26]} {mem_test_m0/wr_burst_data[27]} {mem_test_m0/wr_burst_data[28]} {mem_test_m0/wr_burst_data[29]} {mem_test_m0/wr_burst_data[30]} {mem_test_m0/wr_burst_data[31]} {mem_test_m0/wr_burst_data[32]} {mem_test_m0/wr_burst_data[33]} {mem_test_m0/wr_burst_data[34]} {mem_test_m0/wr_burst_data[35]} {mem_test_m0/wr_burst_data[36]} {mem_test_m0/wr_burst_data[37]} {mem_test_m0/wr_burst_data[38]} {mem_test_m0/wr_burst_data[39]} {mem_test_m0/wr_burst_data[40]} {mem_test_m0/wr_burst_data[41]} {mem_test_m0/wr_burst_data[42]} {mem_test_m0/wr_burst_data[43]} {mem_test_m0/wr_burst_data[44]} {mem_test_m0/wr_burst_data[45]} {mem_test_m0/wr_burst_data[46]} {mem_test_m0/wr_burst_data[47]} {mem_test_m0/wr_burst_data[48]} {mem_test_m0/wr_burst_data[49]} {mem_test_m0/wr_burst_data[50]} {mem_test_m0/wr_burst_data[51]} {mem_test_m0/wr_burst_data[52]} {mem_test_m0/wr_burst_data[53]} {mem_test_m0/wr_burst_data[54]} {mem_test_m0/wr_burst_data[55]} {mem_test_m0/wr_burst_data[56]} {mem_test_m0/wr_burst_data[57]} {mem_test_m0/wr_burst_data[58]} {mem_test_m0/wr_burst_data[59]} {mem_test_m0/wr_burst_data[60]} {mem_test_m0/wr_burst_data[61]} {mem_test_m0/wr_burst_data[62]} {mem_test_m0/wr_burst_data[63]} {mem_test_m0/wr_burst_data[64]} {mem_test_m0/wr_burst_data[65]} {mem_test_m0/wr_burst_data[66]} {mem_test_m0/wr_burst_data[67]} {mem_test_m0/wr_burst_data[68]} {mem_test_m0/wr_burst_data[69]} {mem_test_m0/wr_burst_data[70]} {mem_test_m0/wr_burst_data[71]} {mem_test_m0/wr_burst_data[72]} {mem_test_m0/wr_burst_data[73]} {mem_test_m0/wr_burst_data[74]} {mem_test_m0/wr_burst_data[75]} {mem_test_m0/wr_burst_data[76]} {mem_test_m0/wr_burst_data[77]} {mem_test_m0/wr_burst_data[78]} {mem_test_m0/wr_burst_data[79]} {mem_test_m0/wr_burst_data[80]} {mem_test_m0/wr_burst_data[81]} {mem_test_m0/wr_burst_data[82]} {mem_test_m0/wr_burst_data[83]} {mem_test_m0/wr_burst_data[84]} {mem_test_m0/wr_burst_data[85]} {mem_test_m0/wr_burst_data[86]} {mem_test_m0/wr_burst_data[87]} {mem_test_m0/wr_burst_data[88]} {mem_test_m0/wr_burst_data[89]} {mem_test_m0/wr_burst_data[90]} {mem_test_m0/wr_burst_data[91]} {mem_test_m0/wr_burst_data[92]} {mem_test_m0/wr_burst_data[93]} {mem_test_m0/wr_burst_data[94]} {mem_test_m0/wr_burst_data[95]} {mem_test_m0/wr_burst_data[96]} {mem_test_m0/wr_burst_data[97]} {mem_test_m0/wr_burst_data[98]} {mem_test_m0/wr_burst_data[99]} {mem_test_m0/wr_burst_data[100]} {mem_test_m0/wr_burst_data[101]} {mem_test_m0/wr_burst_data[102]} {mem_test_m0/wr_burst_data[103]} {mem_test_m0/wr_burst_data[104]} {mem_test_m0/wr_burst_data[105]} {mem_test_m0/wr_burst_data[106]} {mem_test_m0/wr_burst_data[107]} {mem_test_m0/wr_burst_data[108]} {mem_test_m0/wr_burst_data[109]} {mem_test_m0/wr_burst_data[110]} {mem_test_m0/wr_burst_data[111]} {mem_test_m0/wr_burst_data[112]} {mem_test_m0/wr_burst_data[113]} {mem_test_m0/wr_burst_data[114]} {mem_test_m0/wr_burst_data[115]} {mem_test_m0/wr_burst_data[116]} {mem_test_m0/wr_burst_data[117]} {mem_test_m0/wr_burst_data[118]} {mem_test_m0/wr_burst_data[119]} {mem_test_m0/wr_burst_data[120]} {mem_test_m0/wr_burst_data[121]} {mem_test_m0/wr_burst_data[122]} {mem_test_m0/wr_burst_data[123]} {mem_test_m0/wr_burst_data[124]} {mem_test_m0/wr_burst_data[125]} {mem_test_m0/wr_burst_data[126]} {mem_test_m0/wr_burst_data[127]}]]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {mem_test_m0/wr_burst_len[0]} {mem_test_m0/wr_burst_len[1]} {mem_test_m0/wr_burst_len[2]} {mem_test_m0/wr_burst_len[3]} {mem_test_m0/wr_burst_len[4]} {mem_test_m0/wr_burst_len[5]} {mem_test_m0/wr_burst_len[6]} {mem_test_m0/wr_burst_len[7]} {mem_test_m0/wr_burst_len[8]} {mem_test_m0/wr_burst_len[9]}]]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 28 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {mem_test_m0/wr_burst_addr[0]} {mem_test_m0/wr_burst_addr[1]} {mem_test_m0/wr_burst_addr[2]} {mem_test_m0/wr_burst_addr[3]} {mem_test_m0/wr_burst_addr[4]} {mem_test_m0/wr_burst_addr[5]} {mem_test_m0/wr_burst_addr[6]} {mem_test_m0/wr_burst_addr[7]} {mem_test_m0/wr_burst_addr[8]} {mem_test_m0/wr_burst_addr[9]} {mem_test_m0/wr_burst_addr[10]} {mem_test_m0/wr_burst_addr[11]} {mem_test_m0/wr_burst_addr[12]} {mem_test_m0/wr_burst_addr[13]} {mem_test_m0/wr_burst_addr[14]} {mem_test_m0/wr_burst_addr[15]} {mem_test_m0/wr_burst_addr[16]} {mem_test_m0/wr_burst_addr[17]} {mem_test_m0/wr_burst_addr[18]} {mem_test_m0/wr_burst_addr[19]} {mem_test_m0/wr_burst_addr[20]} {mem_test_m0/wr_burst_addr[21]} {mem_test_m0/wr_burst_addr[22]} {mem_test_m0/wr_burst_addr[23]} {mem_test_m0/wr_burst_addr[24]} {mem_test_m0/wr_burst_addr[25]} {mem_test_m0/wr_burst_addr[26]} {mem_test_m0/wr_burst_addr[27]}]]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {mem_test_m0/wr_data_pre_add[0]} {mem_test_m0/wr_data_pre_add[1]} {mem_test_m0/wr_data_pre_add[2]} {mem_test_m0/wr_data_pre_add[3]} {mem_test_m0/wr_data_pre_add[4]} {mem_test_m0/wr_data_pre_add[5]} {mem_test_m0/wr_data_pre_add[6]} {mem_test_m0/wr_data_pre_add[7]} {mem_test_m0/wr_data_pre_add[8]} {mem_test_m0/wr_data_pre_add[9]} {mem_test_m0/wr_data_pre_add[10]} {mem_test_m0/wr_data_pre_add[11]} {mem_test_m0/wr_data_pre_add[12]} {mem_test_m0/wr_data_pre_add[13]} {mem_test_m0/wr_data_pre_add[14]} {mem_test_m0/wr_data_pre_add[15]}]]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list mem_burst_m0/app_en]]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list mem_burst_m0/app_rd_data_end]]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list mem_burst_m0/app_rdy]]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list mem_burst_m0/app_wdf_end]]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list mem_burst_m0/app_wdf_rdy]]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list mem_test_m0/error]]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list init_calib_complete]]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list mem_test_m0/rd_burst_data_valid]]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list mem_test_m0/rd_burst_finish]]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list mem_test_m0/rd_burst_req]]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list mem_test_m0/wr_burst_data_req]]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list mem_test_m0/wr_burst_finish]]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list mem_test_m0/wr_burst_req]]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12 [get_ports sys_rst]
