// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module overlaystream_PackPixel (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        ap_return
);


output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
output  [23:0] ap_return;

assign ap_ready = 1'b1;

assign ap_return = {{{p_read2}, {p_read1}}, {p_read}};

endmodule //overlaystream_PackPixel
