-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_detector is
port (
    src_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    src_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    src_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    dst_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    dst_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    dst_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    threshold : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    threshold_ap_vld : IN STD_LOGIC;
    src_TVALID : IN STD_LOGIC;
    src_TREADY : OUT STD_LOGIC;
    dst_TVALID : OUT STD_LOGIC;
    dst_TREADY : IN STD_LOGIC );
end;


architecture behav of edge_detector is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "edge_detector_edge_detector,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.009000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=2102,HLS_SYN_LUT=3159,HLS_VERSION=2020_1}";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal edge_detector_entry3_U0_ap_start : STD_LOGIC;
    signal edge_detector_entry3_U0_ap_done : STD_LOGIC;
    signal edge_detector_entry3_U0_ap_continue : STD_LOGIC;
    signal edge_detector_entry3_U0_ap_idle : STD_LOGIC;
    signal edge_detector_entry3_U0_ap_ready : STD_LOGIC;
    signal edge_detector_entry3_U0_start_out : STD_LOGIC;
    signal edge_detector_entry3_U0_start_write : STD_LOGIC;
    signal edge_detector_entry3_U0_threshold_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal edge_detector_entry3_U0_threshold_out_write : STD_LOGIC;
    signal edge_detector_entry16_U0_ap_start : STD_LOGIC;
    signal edge_detector_entry16_U0_ap_done : STD_LOGIC;
    signal edge_detector_entry16_U0_ap_continue : STD_LOGIC;
    signal edge_detector_entry16_U0_ap_idle : STD_LOGIC;
    signal edge_detector_entry16_U0_ap_ready : STD_LOGIC;
    signal edge_detector_entry16_U0_start_out : STD_LOGIC;
    signal edge_detector_entry16_U0_start_write : STD_LOGIC;
    signal edge_detector_entry16_U0_threshold_read : STD_LOGIC;
    signal edge_detector_entry16_U0_threshold_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal edge_detector_entry16_U0_threshold_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_start : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_done : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_continue : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_idle : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_ready : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_start_out : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_start_write : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_read : STD_LOGIC;
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_V_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_V_out_write : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_ap_start : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_ap_done : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_ap_continue : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_ap_idle : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_ap_ready : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_start_out : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_start_write : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_src_TREADY : STD_LOGIC;
    signal Loop_loop_height_proc14_U0_srcImg_data_din : STD_LOGIC_VECTOR (23 downto 0);
    signal Loop_loop_height_proc14_U0_srcImg_data_write : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_start : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_done : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_continue : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_idle : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_ready : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_start_out : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_start_write : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_srcImg_4228_read : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_grayImg_4230_din : STD_LOGIC_VECTOR (7 downto 0);
    signal xfrgb2gray_1080_1920_U0_grayImg_4230_write : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_start : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_done : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_continue : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_idle : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_ready : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_start_out : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_start_write : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_grayImg_4230_read : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_x_4231_din : STD_LOGIC_VECTOR (7 downto 0);
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_x_4231_write : STD_LOGIC;
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_y_4232_din : STD_LOGIC_VECTOR (7 downto 0);
    signal xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_y_4232_write : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_ap_start : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_ap_done : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_ap_continue : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_ap_idle : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_ap_ready : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_sobelImg_x_4231_read : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_sobelImg_y_4232_read : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_sobelImg_4233_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AddWeightedKernel_1080_1920_U0_sobelImg_4233_write : STD_LOGIC;
    signal thresholding_1080_1920_U0_ap_start : STD_LOGIC;
    signal thresholding_1080_1920_U0_ap_done : STD_LOGIC;
    signal thresholding_1080_1920_U0_ap_continue : STD_LOGIC;
    signal thresholding_1080_1920_U0_ap_idle : STD_LOGIC;
    signal thresholding_1080_1920_U0_ap_ready : STD_LOGIC;
    signal thresholding_1080_1920_U0_start_out : STD_LOGIC;
    signal thresholding_1080_1920_U0_start_write : STD_LOGIC;
    signal thresholding_1080_1920_U0_sobelImg_4233_read : STD_LOGIC;
    signal thresholding_1080_1920_U0_thresholdImg_4234_din : STD_LOGIC_VECTOR (7 downto 0);
    signal thresholding_1080_1920_U0_thresholdImg_4234_write : STD_LOGIC;
    signal thresholding_1080_1920_U0_threshold_read : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_start : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_done : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_continue : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_idle : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_ready : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_start_out : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_start_write : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_thresholdImg_4234_read : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_rgbSobel_4229_din : STD_LOGIC_VECTOR (23 downto 0);
    signal xfgray2rgb_1080_1920_U0_rgbSobel_4229_write : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_ap_start : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_ap_done : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_ap_continue : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_ap_idle : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_ap_ready : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_rgbSobel_data_read : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_dst_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal Loop_loop_height_proc1315_U0_dst_TVALID : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_dst_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal Loop_loop_height_proc1315_U0_dst_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal Loop_loop_height_proc1315_U0_dst_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_loop_height_proc1315_U0_dst_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_loop_height_proc1315_U0_dst_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_loop_height_proc1315_U0_dst_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal threshold_c1_full_n : STD_LOGIC;
    signal threshold_c1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal threshold_c1_empty_n : STD_LOGIC;
    signal threshold_c_full_n : STD_LOGIC;
    signal threshold_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal threshold_c_empty_n : STD_LOGIC;
    signal threshold_V_c_full_n : STD_LOGIC;
    signal threshold_V_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal threshold_V_c_empty_n : STD_LOGIC;
    signal srcImg_data_full_n : STD_LOGIC;
    signal srcImg_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal srcImg_data_empty_n : STD_LOGIC;
    signal grayImg_data_full_n : STD_LOGIC;
    signal grayImg_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grayImg_data_empty_n : STD_LOGIC;
    signal sobelImg_x_data_full_n : STD_LOGIC;
    signal sobelImg_x_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobelImg_x_data_empty_n : STD_LOGIC;
    signal sobelImg_y_data_full_n : STD_LOGIC;
    signal sobelImg_y_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobelImg_y_data_empty_n : STD_LOGIC;
    signal sobelImg_data_full_n : STD_LOGIC;
    signal sobelImg_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobelImg_data_empty_n : STD_LOGIC;
    signal thresholdImg_data_full_n : STD_LOGIC;
    signal thresholdImg_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal thresholdImg_data_empty_n : STD_LOGIC;
    signal rgbSobel_data_full_n : STD_LOGIC;
    signal rgbSobel_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal rgbSobel_data_empty_n : STD_LOGIC;
    signal start_for_edge_detector_entry16_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_edge_detector_entry16_U0_full_n : STD_LOGIC;
    signal start_for_edge_detector_entry16_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_edge_detector_entry16_U0_empty_n : STD_LOGIC;
    signal start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_full_n : STD_LOGIC;
    signal start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_empty_n : STD_LOGIC;
    signal start_for_thresholding_1080_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_thresholding_1080_1920_U0_full_n : STD_LOGIC;
    signal start_for_thresholding_1080_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_thresholding_1080_1920_U0_empty_n : STD_LOGIC;
    signal start_for_xfrgb2gray_1080_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfrgb2gray_1080_1920_U0_full_n : STD_LOGIC;
    signal start_for_xfrgb2gray_1080_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfrgb2gray_1080_1920_U0_empty_n : STD_LOGIC;
    signal start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_full_n : STD_LOGIC;
    signal start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_empty_n : STD_LOGIC;
    signal start_for_AddWeightedKernel_1080_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_AddWeightedKernel_1080_1920_U0_full_n : STD_LOGIC;
    signal start_for_AddWeightedKernel_1080_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_AddWeightedKernel_1080_1920_U0_empty_n : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_start_full_n : STD_LOGIC;
    signal AddWeightedKernel_1080_1920_U0_start_write : STD_LOGIC;
    signal start_for_xfgray2rgb_1080_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfgray2rgb_1080_1920_U0_full_n : STD_LOGIC;
    signal start_for_xfgray2rgb_1080_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfgray2rgb_1080_1920_U0_empty_n : STD_LOGIC;
    signal start_for_Loop_loop_height_proc1315_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_loop_height_proc1315_U0_full_n : STD_LOGIC;
    signal start_for_Loop_loop_height_proc1315_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_loop_height_proc1315_U0_empty_n : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_start_full_n : STD_LOGIC;
    signal Loop_loop_height_proc1315_U0_start_write : STD_LOGIC;

    component edge_detector_edge_detector_entry3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        threshold : IN STD_LOGIC_VECTOR (7 downto 0);
        threshold_ap_vld : IN STD_LOGIC;
        threshold_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        threshold_out_full_n : IN STD_LOGIC;
        threshold_out_write : OUT STD_LOGIC );
    end component;


    component edge_detector_edge_detector_entry16 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        threshold_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        threshold_empty_n : IN STD_LOGIC;
        threshold_read : OUT STD_LOGIC;
        threshold_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        threshold_out_full_n : IN STD_LOGIC;
        threshold_out_write : OUT STD_LOGIC );
    end component;


    component edge_detector_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        threshold_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        threshold_empty_n : IN STD_LOGIC;
        threshold_read : OUT STD_LOGIC;
        threshold_V_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        threshold_V_out_full_n : IN STD_LOGIC;
        threshold_V_out_write : OUT STD_LOGIC );
    end component;


    component edge_detector_Loop_loop_height_proc14 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        src_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        src_TVALID : IN STD_LOGIC;
        src_TREADY : OUT STD_LOGIC;
        src_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        src_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        srcImg_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        srcImg_data_full_n : IN STD_LOGIC;
        srcImg_data_write : OUT STD_LOGIC );
    end component;


    component edge_detector_xfrgb2gray_1080_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        srcImg_4228_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        srcImg_4228_empty_n : IN STD_LOGIC;
        srcImg_4228_read : OUT STD_LOGIC;
        grayImg_4230_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        grayImg_4230_full_n : IN STD_LOGIC;
        grayImg_4230_write : OUT STD_LOGIC );
    end component;


    component edge_detector_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        grayImg_4230_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        grayImg_4230_empty_n : IN STD_LOGIC;
        grayImg_4230_read : OUT STD_LOGIC;
        sobelImg_x_4231_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        sobelImg_x_4231_full_n : IN STD_LOGIC;
        sobelImg_x_4231_write : OUT STD_LOGIC;
        sobelImg_y_4232_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        sobelImg_y_4232_full_n : IN STD_LOGIC;
        sobelImg_y_4232_write : OUT STD_LOGIC );
    end component;


    component edge_detector_AddWeightedKernel_1080_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sobelImg_x_4231_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        sobelImg_x_4231_empty_n : IN STD_LOGIC;
        sobelImg_x_4231_read : OUT STD_LOGIC;
        sobelImg_y_4232_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        sobelImg_y_4232_empty_n : IN STD_LOGIC;
        sobelImg_y_4232_read : OUT STD_LOGIC;
        sobelImg_4233_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        sobelImg_4233_full_n : IN STD_LOGIC;
        sobelImg_4233_write : OUT STD_LOGIC );
    end component;


    component edge_detector_thresholding_1080_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        sobelImg_4233_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        sobelImg_4233_empty_n : IN STD_LOGIC;
        sobelImg_4233_read : OUT STD_LOGIC;
        thresholdImg_4234_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        thresholdImg_4234_full_n : IN STD_LOGIC;
        thresholdImg_4234_write : OUT STD_LOGIC;
        threshold_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        threshold_empty_n : IN STD_LOGIC;
        threshold_read : OUT STD_LOGIC );
    end component;


    component edge_detector_xfgray2rgb_1080_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        thresholdImg_4234_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        thresholdImg_4234_empty_n : IN STD_LOGIC;
        thresholdImg_4234_read : OUT STD_LOGIC;
        rgbSobel_4229_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        rgbSobel_4229_full_n : IN STD_LOGIC;
        rgbSobel_4229_write : OUT STD_LOGIC );
    end component;


    component edge_detector_Loop_loop_height_proc1315 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rgbSobel_data_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        rgbSobel_data_empty_n : IN STD_LOGIC;
        rgbSobel_data_read : OUT STD_LOGIC;
        dst_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        dst_TVALID : OUT STD_LOGIC;
        dst_TREADY : IN STD_LOGIC;
        dst_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        dst_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component edge_detector_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_fifo_w8_d5_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_fifo_w24_d1920_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_fifo_w8_d1920_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_edge_detector_entry16_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_thresholding_1080_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_xfrgb2gray_1080_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_AddWeightedKernel_1080_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_xfgray2rgb_1080_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_detector_start_for_Loop_loop_height_proc1315_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    edge_detector_entry3_U0 : component edge_detector_edge_detector_entry3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => edge_detector_entry3_U0_ap_start,
        start_full_n => start_for_edge_detector_entry16_U0_full_n,
        ap_done => edge_detector_entry3_U0_ap_done,
        ap_continue => edge_detector_entry3_U0_ap_continue,
        ap_idle => edge_detector_entry3_U0_ap_idle,
        ap_ready => edge_detector_entry3_U0_ap_ready,
        start_out => edge_detector_entry3_U0_start_out,
        start_write => edge_detector_entry3_U0_start_write,
        threshold => threshold,
        threshold_ap_vld => threshold_ap_vld,
        threshold_out_din => edge_detector_entry3_U0_threshold_out_din,
        threshold_out_full_n => threshold_c1_full_n,
        threshold_out_write => edge_detector_entry3_U0_threshold_out_write);

    edge_detector_entry16_U0 : component edge_detector_edge_detector_entry16
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => edge_detector_entry16_U0_ap_start,
        start_full_n => start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_full_n,
        ap_done => edge_detector_entry16_U0_ap_done,
        ap_continue => edge_detector_entry16_U0_ap_continue,
        ap_idle => edge_detector_entry16_U0_ap_idle,
        ap_ready => edge_detector_entry16_U0_ap_ready,
        start_out => edge_detector_entry16_U0_start_out,
        start_write => edge_detector_entry16_U0_start_write,
        threshold_dout => threshold_c1_dout,
        threshold_empty_n => threshold_c1_empty_n,
        threshold_read => edge_detector_entry16_U0_threshold_read,
        threshold_out_din => edge_detector_entry16_U0_threshold_out_din,
        threshold_out_full_n => threshold_c_full_n,
        threshold_out_write => edge_detector_entry16_U0_threshold_out_write);

    Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0 : component edge_detector_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_start,
        start_full_n => start_for_thresholding_1080_1920_U0_full_n,
        ap_done => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_done,
        ap_continue => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_continue,
        ap_idle => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_idle,
        ap_ready => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_ready,
        start_out => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_start_out,
        start_write => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_start_write,
        threshold_dout => threshold_c_dout,
        threshold_empty_n => threshold_c_empty_n,
        threshold_read => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_read,
        threshold_V_out_din => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_V_out_din,
        threshold_V_out_full_n => threshold_V_c_full_n,
        threshold_V_out_write => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_V_out_write);

    Loop_loop_height_proc14_U0 : component edge_detector_Loop_loop_height_proc14
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_loop_height_proc14_U0_ap_start,
        start_full_n => start_for_xfrgb2gray_1080_1920_U0_full_n,
        ap_done => Loop_loop_height_proc14_U0_ap_done,
        ap_continue => Loop_loop_height_proc14_U0_ap_continue,
        ap_idle => Loop_loop_height_proc14_U0_ap_idle,
        ap_ready => Loop_loop_height_proc14_U0_ap_ready,
        start_out => Loop_loop_height_proc14_U0_start_out,
        start_write => Loop_loop_height_proc14_U0_start_write,
        src_TDATA => src_TDATA,
        src_TVALID => src_TVALID,
        src_TREADY => Loop_loop_height_proc14_U0_src_TREADY,
        src_TKEEP => src_TKEEP,
        src_TSTRB => src_TSTRB,
        src_TUSER => src_TUSER,
        src_TLAST => src_TLAST,
        src_TID => src_TID,
        src_TDEST => src_TDEST,
        srcImg_data_din => Loop_loop_height_proc14_U0_srcImg_data_din,
        srcImg_data_full_n => srcImg_data_full_n,
        srcImg_data_write => Loop_loop_height_proc14_U0_srcImg_data_write);

    xfrgb2gray_1080_1920_U0 : component edge_detector_xfrgb2gray_1080_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfrgb2gray_1080_1920_U0_ap_start,
        start_full_n => start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_full_n,
        ap_done => xfrgb2gray_1080_1920_U0_ap_done,
        ap_continue => xfrgb2gray_1080_1920_U0_ap_continue,
        ap_idle => xfrgb2gray_1080_1920_U0_ap_idle,
        ap_ready => xfrgb2gray_1080_1920_U0_ap_ready,
        start_out => xfrgb2gray_1080_1920_U0_start_out,
        start_write => xfrgb2gray_1080_1920_U0_start_write,
        srcImg_4228_dout => srcImg_data_dout,
        srcImg_4228_empty_n => srcImg_data_empty_n,
        srcImg_4228_read => xfrgb2gray_1080_1920_U0_srcImg_4228_read,
        grayImg_4230_din => xfrgb2gray_1080_1920_U0_grayImg_4230_din,
        grayImg_4230_full_n => grayImg_data_full_n,
        grayImg_4230_write => xfrgb2gray_1080_1920_U0_grayImg_4230_write);

    xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0 : component edge_detector_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_start,
        start_full_n => start_for_AddWeightedKernel_1080_1920_U0_full_n,
        ap_done => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_done,
        ap_continue => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_continue,
        ap_idle => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_idle,
        ap_ready => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_ready,
        start_out => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_start_out,
        start_write => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_start_write,
        grayImg_4230_dout => grayImg_data_dout,
        grayImg_4230_empty_n => grayImg_data_empty_n,
        grayImg_4230_read => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_grayImg_4230_read,
        sobelImg_x_4231_din => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_x_4231_din,
        sobelImg_x_4231_full_n => sobelImg_x_data_full_n,
        sobelImg_x_4231_write => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_x_4231_write,
        sobelImg_y_4232_din => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_y_4232_din,
        sobelImg_y_4232_full_n => sobelImg_y_data_full_n,
        sobelImg_y_4232_write => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_y_4232_write);

    AddWeightedKernel_1080_1920_U0 : component edge_detector_AddWeightedKernel_1080_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AddWeightedKernel_1080_1920_U0_ap_start,
        ap_done => AddWeightedKernel_1080_1920_U0_ap_done,
        ap_continue => AddWeightedKernel_1080_1920_U0_ap_continue,
        ap_idle => AddWeightedKernel_1080_1920_U0_ap_idle,
        ap_ready => AddWeightedKernel_1080_1920_U0_ap_ready,
        sobelImg_x_4231_dout => sobelImg_x_data_dout,
        sobelImg_x_4231_empty_n => sobelImg_x_data_empty_n,
        sobelImg_x_4231_read => AddWeightedKernel_1080_1920_U0_sobelImg_x_4231_read,
        sobelImg_y_4232_dout => sobelImg_y_data_dout,
        sobelImg_y_4232_empty_n => sobelImg_y_data_empty_n,
        sobelImg_y_4232_read => AddWeightedKernel_1080_1920_U0_sobelImg_y_4232_read,
        sobelImg_4233_din => AddWeightedKernel_1080_1920_U0_sobelImg_4233_din,
        sobelImg_4233_full_n => sobelImg_data_full_n,
        sobelImg_4233_write => AddWeightedKernel_1080_1920_U0_sobelImg_4233_write);

    thresholding_1080_1920_U0 : component edge_detector_thresholding_1080_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => thresholding_1080_1920_U0_ap_start,
        start_full_n => start_for_xfgray2rgb_1080_1920_U0_full_n,
        ap_done => thresholding_1080_1920_U0_ap_done,
        ap_continue => thresholding_1080_1920_U0_ap_continue,
        ap_idle => thresholding_1080_1920_U0_ap_idle,
        ap_ready => thresholding_1080_1920_U0_ap_ready,
        start_out => thresholding_1080_1920_U0_start_out,
        start_write => thresholding_1080_1920_U0_start_write,
        sobelImg_4233_dout => sobelImg_data_dout,
        sobelImg_4233_empty_n => sobelImg_data_empty_n,
        sobelImg_4233_read => thresholding_1080_1920_U0_sobelImg_4233_read,
        thresholdImg_4234_din => thresholding_1080_1920_U0_thresholdImg_4234_din,
        thresholdImg_4234_full_n => thresholdImg_data_full_n,
        thresholdImg_4234_write => thresholding_1080_1920_U0_thresholdImg_4234_write,
        threshold_dout => threshold_V_c_dout,
        threshold_empty_n => threshold_V_c_empty_n,
        threshold_read => thresholding_1080_1920_U0_threshold_read);

    xfgray2rgb_1080_1920_U0 : component edge_detector_xfgray2rgb_1080_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfgray2rgb_1080_1920_U0_ap_start,
        start_full_n => start_for_Loop_loop_height_proc1315_U0_full_n,
        ap_done => xfgray2rgb_1080_1920_U0_ap_done,
        ap_continue => xfgray2rgb_1080_1920_U0_ap_continue,
        ap_idle => xfgray2rgb_1080_1920_U0_ap_idle,
        ap_ready => xfgray2rgb_1080_1920_U0_ap_ready,
        start_out => xfgray2rgb_1080_1920_U0_start_out,
        start_write => xfgray2rgb_1080_1920_U0_start_write,
        thresholdImg_4234_dout => thresholdImg_data_dout,
        thresholdImg_4234_empty_n => thresholdImg_data_empty_n,
        thresholdImg_4234_read => xfgray2rgb_1080_1920_U0_thresholdImg_4234_read,
        rgbSobel_4229_din => xfgray2rgb_1080_1920_U0_rgbSobel_4229_din,
        rgbSobel_4229_full_n => rgbSobel_data_full_n,
        rgbSobel_4229_write => xfgray2rgb_1080_1920_U0_rgbSobel_4229_write);

    Loop_loop_height_proc1315_U0 : component edge_detector_Loop_loop_height_proc1315
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_loop_height_proc1315_U0_ap_start,
        ap_done => Loop_loop_height_proc1315_U0_ap_done,
        ap_continue => Loop_loop_height_proc1315_U0_ap_continue,
        ap_idle => Loop_loop_height_proc1315_U0_ap_idle,
        ap_ready => Loop_loop_height_proc1315_U0_ap_ready,
        rgbSobel_data_dout => rgbSobel_data_dout,
        rgbSobel_data_empty_n => rgbSobel_data_empty_n,
        rgbSobel_data_read => Loop_loop_height_proc1315_U0_rgbSobel_data_read,
        dst_TDATA => Loop_loop_height_proc1315_U0_dst_TDATA,
        dst_TVALID => Loop_loop_height_proc1315_U0_dst_TVALID,
        dst_TREADY => dst_TREADY,
        dst_TKEEP => Loop_loop_height_proc1315_U0_dst_TKEEP,
        dst_TSTRB => Loop_loop_height_proc1315_U0_dst_TSTRB,
        dst_TUSER => Loop_loop_height_proc1315_U0_dst_TUSER,
        dst_TLAST => Loop_loop_height_proc1315_U0_dst_TLAST,
        dst_TID => Loop_loop_height_proc1315_U0_dst_TID,
        dst_TDEST => Loop_loop_height_proc1315_U0_dst_TDEST);

    threshold_c1_U : component edge_detector_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => edge_detector_entry3_U0_threshold_out_din,
        if_full_n => threshold_c1_full_n,
        if_write => edge_detector_entry3_U0_threshold_out_write,
        if_dout => threshold_c1_dout,
        if_empty_n => threshold_c1_empty_n,
        if_read => edge_detector_entry16_U0_threshold_read);

    threshold_c_U : component edge_detector_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => edge_detector_entry16_U0_threshold_out_din,
        if_full_n => threshold_c_full_n,
        if_write => edge_detector_entry16_U0_threshold_out_write,
        if_dout => threshold_c_dout,
        if_empty_n => threshold_c_empty_n,
        if_read => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_read);

    threshold_V_c_U : component edge_detector_fifo_w8_d5_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_V_out_din,
        if_full_n => threshold_V_c_full_n,
        if_write => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_threshold_V_out_write,
        if_dout => threshold_V_c_dout,
        if_empty_n => threshold_V_c_empty_n,
        if_read => thresholding_1080_1920_U0_threshold_read);

    srcImg_data_U : component edge_detector_fifo_w24_d1920_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_loop_height_proc14_U0_srcImg_data_din,
        if_full_n => srcImg_data_full_n,
        if_write => Loop_loop_height_proc14_U0_srcImg_data_write,
        if_dout => srcImg_data_dout,
        if_empty_n => srcImg_data_empty_n,
        if_read => xfrgb2gray_1080_1920_U0_srcImg_4228_read);

    grayImg_data_U : component edge_detector_fifo_w8_d1920_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xfrgb2gray_1080_1920_U0_grayImg_4230_din,
        if_full_n => grayImg_data_full_n,
        if_write => xfrgb2gray_1080_1920_U0_grayImg_4230_write,
        if_dout => grayImg_data_dout,
        if_empty_n => grayImg_data_empty_n,
        if_read => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_grayImg_4230_read);

    sobelImg_x_data_U : component edge_detector_fifo_w8_d1920_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_x_4231_din,
        if_full_n => sobelImg_x_data_full_n,
        if_write => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_x_4231_write,
        if_dout => sobelImg_x_data_dout,
        if_empty_n => sobelImg_x_data_empty_n,
        if_read => AddWeightedKernel_1080_1920_U0_sobelImg_x_4231_read);

    sobelImg_y_data_U : component edge_detector_fifo_w8_d1920_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_y_4232_din,
        if_full_n => sobelImg_y_data_full_n,
        if_write => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_sobelImg_y_4232_write,
        if_dout => sobelImg_y_data_dout,
        if_empty_n => sobelImg_y_data_empty_n,
        if_read => AddWeightedKernel_1080_1920_U0_sobelImg_y_4232_read);

    sobelImg_data_U : component edge_detector_fifo_w8_d1920_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AddWeightedKernel_1080_1920_U0_sobelImg_4233_din,
        if_full_n => sobelImg_data_full_n,
        if_write => AddWeightedKernel_1080_1920_U0_sobelImg_4233_write,
        if_dout => sobelImg_data_dout,
        if_empty_n => sobelImg_data_empty_n,
        if_read => thresholding_1080_1920_U0_sobelImg_4233_read);

    thresholdImg_data_U : component edge_detector_fifo_w8_d1920_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => thresholding_1080_1920_U0_thresholdImg_4234_din,
        if_full_n => thresholdImg_data_full_n,
        if_write => thresholding_1080_1920_U0_thresholdImg_4234_write,
        if_dout => thresholdImg_data_dout,
        if_empty_n => thresholdImg_data_empty_n,
        if_read => xfgray2rgb_1080_1920_U0_thresholdImg_4234_read);

    rgbSobel_data_U : component edge_detector_fifo_w24_d1920_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xfgray2rgb_1080_1920_U0_rgbSobel_4229_din,
        if_full_n => rgbSobel_data_full_n,
        if_write => xfgray2rgb_1080_1920_U0_rgbSobel_4229_write,
        if_dout => rgbSobel_data_dout,
        if_empty_n => rgbSobel_data_empty_n,
        if_read => Loop_loop_height_proc1315_U0_rgbSobel_data_read);

    start_for_edge_detector_entry16_U0_U : component edge_detector_start_for_edge_detector_entry16_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_edge_detector_entry16_U0_din,
        if_full_n => start_for_edge_detector_entry16_U0_full_n,
        if_write => edge_detector_entry3_U0_start_write,
        if_dout => start_for_edge_detector_entry16_U0_dout,
        if_empty_n => start_for_edge_detector_entry16_U0_empty_n,
        if_read => edge_detector_entry16_U0_ap_ready);

    start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_U : component edge_detector_start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_din,
        if_full_n => start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_full_n,
        if_write => edge_detector_entry16_U0_start_write,
        if_dout => start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_dout,
        if_empty_n => start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_empty_n,
        if_read => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_ready);

    start_for_thresholding_1080_1920_U0_U : component edge_detector_start_for_thresholding_1080_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_thresholding_1080_1920_U0_din,
        if_full_n => start_for_thresholding_1080_1920_U0_full_n,
        if_write => Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_start_write,
        if_dout => start_for_thresholding_1080_1920_U0_dout,
        if_empty_n => start_for_thresholding_1080_1920_U0_empty_n,
        if_read => thresholding_1080_1920_U0_ap_ready);

    start_for_xfrgb2gray_1080_1920_U0_U : component edge_detector_start_for_xfrgb2gray_1080_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfrgb2gray_1080_1920_U0_din,
        if_full_n => start_for_xfrgb2gray_1080_1920_U0_full_n,
        if_write => Loop_loop_height_proc14_U0_start_write,
        if_dout => start_for_xfrgb2gray_1080_1920_U0_dout,
        if_empty_n => start_for_xfrgb2gray_1080_1920_U0_empty_n,
        if_read => xfrgb2gray_1080_1920_U0_ap_ready);

    start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_U : component edge_detector_start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_din,
        if_full_n => start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_full_n,
        if_write => xfrgb2gray_1080_1920_U0_start_write,
        if_dout => start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_dout,
        if_empty_n => start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_empty_n,
        if_read => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_ready);

    start_for_AddWeightedKernel_1080_1920_U0_U : component edge_detector_start_for_AddWeightedKernel_1080_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_AddWeightedKernel_1080_1920_U0_din,
        if_full_n => start_for_AddWeightedKernel_1080_1920_U0_full_n,
        if_write => xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_start_write,
        if_dout => start_for_AddWeightedKernel_1080_1920_U0_dout,
        if_empty_n => start_for_AddWeightedKernel_1080_1920_U0_empty_n,
        if_read => AddWeightedKernel_1080_1920_U0_ap_ready);

    start_for_xfgray2rgb_1080_1920_U0_U : component edge_detector_start_for_xfgray2rgb_1080_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfgray2rgb_1080_1920_U0_din,
        if_full_n => start_for_xfgray2rgb_1080_1920_U0_full_n,
        if_write => thresholding_1080_1920_U0_start_write,
        if_dout => start_for_xfgray2rgb_1080_1920_U0_dout,
        if_empty_n => start_for_xfgray2rgb_1080_1920_U0_empty_n,
        if_read => xfgray2rgb_1080_1920_U0_ap_ready);

    start_for_Loop_loop_height_proc1315_U0_U : component edge_detector_start_for_Loop_loop_height_proc1315_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Loop_loop_height_proc1315_U0_din,
        if_full_n => start_for_Loop_loop_height_proc1315_U0_full_n,
        if_write => xfgray2rgb_1080_1920_U0_start_write,
        if_dout => start_for_Loop_loop_height_proc1315_U0_dout,
        if_empty_n => start_for_Loop_loop_height_proc1315_U0_empty_n,
        if_read => Loop_loop_height_proc1315_U0_ap_ready);




    AddWeightedKernel_1080_1920_U0_ap_continue <= ap_const_logic_1;
    AddWeightedKernel_1080_1920_U0_ap_start <= start_for_AddWeightedKernel_1080_1920_U0_empty_n;
    AddWeightedKernel_1080_1920_U0_start_full_n <= ap_const_logic_1;
    AddWeightedKernel_1080_1920_U0_start_write <= ap_const_logic_0;
    Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_continue <= ap_const_logic_1;
    Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_ap_start <= start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_empty_n;
    Loop_loop_height_proc1315_U0_ap_continue <= ap_const_logic_1;
    Loop_loop_height_proc1315_U0_ap_start <= start_for_Loop_loop_height_proc1315_U0_empty_n;
    Loop_loop_height_proc1315_U0_start_full_n <= ap_const_logic_1;
    Loop_loop_height_proc1315_U0_start_write <= ap_const_logic_0;
    Loop_loop_height_proc14_U0_ap_continue <= ap_const_logic_1;
    Loop_loop_height_proc14_U0_ap_start <= ap_const_logic_1;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_0;
    dst_TDATA <= Loop_loop_height_proc1315_U0_dst_TDATA;
    dst_TDEST <= Loop_loop_height_proc1315_U0_dst_TDEST;
    dst_TID <= Loop_loop_height_proc1315_U0_dst_TID;
    dst_TKEEP <= Loop_loop_height_proc1315_U0_dst_TKEEP;
    dst_TLAST <= Loop_loop_height_proc1315_U0_dst_TLAST;
    dst_TSTRB <= Loop_loop_height_proc1315_U0_dst_TSTRB;
    dst_TUSER <= Loop_loop_height_proc1315_U0_dst_TUSER;
    dst_TVALID <= Loop_loop_height_proc1315_U0_dst_TVALID;
    edge_detector_entry16_U0_ap_continue <= ap_const_logic_1;
    edge_detector_entry16_U0_ap_start <= start_for_edge_detector_entry16_U0_empty_n;
    edge_detector_entry3_U0_ap_continue <= ap_const_logic_1;
    edge_detector_entry3_U0_ap_start <= ap_const_logic_1;
    src_TREADY <= Loop_loop_height_proc14_U0_src_TREADY;
    start_for_AddWeightedKernel_1080_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Block_ZN2xf2cv6ScalarILi3E7ap_uintILi24EEEC2Ev_exit_i5067_proc_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Loop_loop_height_proc1315_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_edge_detector_entry16_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_thresholding_1080_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xfgray2rgb_1080_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xfrgb2gray_1080_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    thresholding_1080_1920_U0_ap_continue <= ap_const_logic_1;
    thresholding_1080_1920_U0_ap_start <= start_for_thresholding_1080_1920_U0_empty_n;
    xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_continue <= ap_const_logic_1;
    xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_ap_start <= start_for_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_U0_empty_n;
    xfgray2rgb_1080_1920_U0_ap_continue <= ap_const_logic_1;
    xfgray2rgb_1080_1920_U0_ap_start <= start_for_xfgray2rgb_1080_1920_U0_empty_n;
    xfrgb2gray_1080_1920_U0_ap_continue <= ap_const_logic_1;
    xfrgb2gray_1080_1920_U0_ap_start <= start_for_xfrgb2gray_1080_1920_U0_empty_n;
end behav;
