# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/gt/gt.xci
# IP: The module: 'gt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/gt/synth/gt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/gt/synth/gt.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/gt/gt.xci
# IP: The module: 'gt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/gt/synth/gt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/gt/synth/gt.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
