set_property SRC_FILE_INFO {cfile:e:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/sys_clock/sys_clock/sys_clock_in_context.xdc rfile:../../../gt_test.srcs/sources_1/ip/sys_clock/sys_clock/sys_clock_in_context.xdc id:1 order:EARLY scoped_inst:sys_clock_m0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/ip/gt/gt/gt_in_context.xdc rfile:../../../gt_test.srcs/sources_1/ip/gt/gt/gt_in_context.xdc id:2 order:EARLY scoped_inst:gt_exdes_m0/example_wrapper_inst/gt_inst} [current_design]
set_property SRC_FILE_INFO {cfile:E:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/constrs_1/new/system.xdc rfile:../../../gt_test.srcs/constrs_1/new/system.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:E:/XilinxPrj/serdes/AXU5EV_P/gt_12p5g_test/gt_test.srcs/sources_1/imports/gt_example_top.xdc rfile:../../../gt_test.srcs/sources_1/imports/gt_example_top.xdc id:4} [current_design]
current_instance sys_clock_m0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 2.500 5.000} [get_ports {}]
current_instance
current_instance gt_exdes_m0/example_wrapper_inst/gt_inst
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.200 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.200 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.200 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.200 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports gtrefclk00_in[0]] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports gtrefclk00_in[0]] -edges {1 2 3} -edge_shift {0.000 -3.920 -7.840} [get_ports {}]
current_instance
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D12 [get_ports {tx_disable[0]}]
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports mgtrefclk_n]
set_property src_info {type:XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports mgtrefclk_p]
set_property src_info {type:XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5 [get_ports sys_clk_p]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5 [get_ports sys_clk_n]
