-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity detectCorner_xfrgb2gray_1080_1920_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_in_4217_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img_in_4217_empty_n : IN STD_LOGIC;
    img_in_4217_read : OUT STD_LOGIC;
    img_gray_src_4221_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_gray_src_4221_full_n : IN STD_LOGIC;
    img_gray_src_4221_write : OUT STD_LOGIC;
    img_rgb_src_4219_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    img_rgb_src_4219_full_n : IN STD_LOGIC;
    img_rgb_src_4219_write : OUT STD_LOGIC );
end;


architecture behav of detectCorner_xfrgb2gray_1080_1920_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv21_1FA400 : STD_LOGIC_VECTOR (20 downto 0) := "111111010010000000000";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv22_2646 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010011001000110";
    constant ap_const_lv20_E98 : STD_LOGIC_VECTOR (19 downto 0) := "00000000111010011000";
    constant ap_const_lv23_4B23 : STD_LOGIC_VECTOR (22 downto 0) := "00000000100101100100011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal img_in_4217_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln37_reg_166 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_gray_src_4221_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal icmp_ln37_reg_166_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal img_rgb_src_4219_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_78 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln37_fu_95_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln37_reg_166_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_166_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_166_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_166_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln37_fu_101_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_V_reg_175 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_V_reg_175_pp0_iter2_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_V_reg_175_pp0_iter3_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_V_reg_175_pp0_iter4_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_V_reg_175_pp0_iter5_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal rgb_V_1_reg_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal rgb_V_1_reg_180_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal rgb_V_2_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_142_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal call_ret_ExtractPixel_fu_89_ap_ready : STD_LOGIC;
    signal call_ret_ExtractPixel_fu_89_ap_return_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_ExtractPixel_fu_89_ap_return_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_ExtractPixel_fu_89_ap_return_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_148_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_157_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_fu_142_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_142_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_148_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_148_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_157_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_157_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_157_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_142_ce : STD_LOGIC;
    signal grp_fu_148_ce : STD_LOGIC;
    signal grp_fu_157_ce : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_142_p00 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_148_p00 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_157_p00 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_fu_157_p20 : STD_LOGIC_VECTOR (22 downto 0);

    component detectCorner_ExtractPixel IS
    port (
        ap_ready : OUT STD_LOGIC;
        src_read : IN STD_LOGIC_VECTOR (23 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component detectCorner_mul_mul_8ns_15ns_22_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component detectCorner_mac_muladd_8ns_13ns_22ns_22_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (21 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component detectCorner_mac_muladd_8ns_16ns_22ns_23_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (21 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;



begin
    call_ret_ExtractPixel_fu_89 : component detectCorner_ExtractPixel
    port map (
        ap_ready => call_ret_ExtractPixel_fu_89_ap_ready,
        src_read => img_in_4217_dout,
        ap_return_0 => call_ret_ExtractPixel_fu_89_ap_return_0,
        ap_return_1 => call_ret_ExtractPixel_fu_89_ap_return_1,
        ap_return_2 => call_ret_ExtractPixel_fu_89_ap_return_2);

    mul_mul_8ns_15ns_22_4_1_U13 : component detectCorner_mul_mul_8ns_15ns_22_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 15,
        dout_WIDTH => 22)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_142_p0,
        din1 => grp_fu_142_p1,
        ce => grp_fu_142_ce,
        dout => grp_fu_142_p2);

    mac_muladd_8ns_13ns_22ns_22_4_1_U14 : component detectCorner_mac_muladd_8ns_13ns_22ns_22_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 13,
        din2_WIDTH => 22,
        dout_WIDTH => 22)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_148_p0,
        din1 => grp_fu_148_p1,
        din2 => grp_fu_142_p2,
        ce => grp_fu_148_ce,
        dout => grp_fu_148_p3);

    mac_muladd_8ns_16ns_22ns_23_4_1_U15 : component detectCorner_mac_muladd_8ns_16ns_22ns_23_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 16,
        din2_WIDTH => 22,
        dout_WIDTH => 23)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_157_p0,
        din1 => grp_fu_157_p1,
        din2 => grp_fu_157_p2,
        ce => grp_fu_157_ce,
        dout => grp_fu_157_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln37_fu_95_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_reg_78 <= add_ln37_fu_101_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_78 <= ap_const_lv21_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln37_reg_166 <= icmp_ln37_fu_95_p2;
                icmp_ln37_reg_166_pp0_iter1_reg <= icmp_ln37_reg_166;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln37_reg_166_pp0_iter2_reg <= icmp_ln37_reg_166_pp0_iter1_reg;
                icmp_ln37_reg_166_pp0_iter3_reg <= icmp_ln37_reg_166_pp0_iter2_reg;
                icmp_ln37_reg_166_pp0_iter4_reg <= icmp_ln37_reg_166_pp0_iter3_reg;
                icmp_ln37_reg_166_pp0_iter5_reg <= icmp_ln37_reg_166_pp0_iter4_reg;
                rgb_V_1_reg_180_pp0_iter2_reg <= rgb_V_1_reg_180;
                tmp_V_reg_175_pp0_iter2_reg <= tmp_V_reg_175;
                tmp_V_reg_175_pp0_iter3_reg <= tmp_V_reg_175_pp0_iter2_reg;
                tmp_V_reg_175_pp0_iter4_reg <= tmp_V_reg_175_pp0_iter3_reg;
                tmp_V_reg_175_pp0_iter5_reg <= tmp_V_reg_175_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln37_reg_166 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                rgb_V_1_reg_180 <= call_ret_ExtractPixel_fu_89_ap_return_1;
                rgb_V_2_reg_185 <= call_ret_ExtractPixel_fu_89_ap_return_2;
                tmp_V_reg_175 <= img_in_4217_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, icmp_ln37_fu_95_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln37_fu_95_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln37_fu_95_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln37_fu_101_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_78) + unsigned(ap_const_lv21_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state9 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(img_in_4217_empty_n, img_gray_src_4221_full_n, img_rgb_src_4219_full_n, ap_enable_reg_pp0_iter1, icmp_ln37_reg_166, ap_enable_reg_pp0_iter6, icmp_ln37_reg_166_pp0_iter5_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_rgb_src_4219_full_n = ap_const_logic_0)) or ((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_gray_src_4221_full_n = ap_const_logic_0)))) or ((icmp_ln37_reg_166 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (img_in_4217_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(img_in_4217_empty_n, img_gray_src_4221_full_n, img_rgb_src_4219_full_n, ap_enable_reg_pp0_iter1, icmp_ln37_reg_166, ap_enable_reg_pp0_iter6, icmp_ln37_reg_166_pp0_iter5_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_rgb_src_4219_full_n = ap_const_logic_0)) or ((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_gray_src_4221_full_n = ap_const_logic_0)))) or ((icmp_ln37_reg_166 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (img_in_4217_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(img_in_4217_empty_n, img_gray_src_4221_full_n, img_rgb_src_4219_full_n, ap_enable_reg_pp0_iter1, icmp_ln37_reg_166, ap_enable_reg_pp0_iter6, icmp_ln37_reg_166_pp0_iter5_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_rgb_src_4219_full_n = ap_const_logic_0)) or ((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_gray_src_4221_full_n = ap_const_logic_0)))) or ((icmp_ln37_reg_166 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (img_in_4217_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(img_in_4217_empty_n, icmp_ln37_reg_166)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln37_reg_166 = ap_const_lv1_0) and (img_in_4217_empty_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter6_assign_proc : process(img_gray_src_4221_full_n, img_rgb_src_4219_full_n, icmp_ln37_reg_166_pp0_iter5_reg)
    begin
                ap_block_state8_pp0_stage0_iter6 <= (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_rgb_src_4219_full_n = ap_const_logic_0)) or ((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (img_gray_src_4221_full_n = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln37_fu_95_p2)
    begin
        if ((icmp_ln37_fu_95_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_142_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_142_ce <= ap_const_logic_1;
        else 
            grp_fu_142_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_142_p0 <= grp_fu_142_p00(8 - 1 downto 0);
    grp_fu_142_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(call_ret_ExtractPixel_fu_89_ap_return_0),22));
    grp_fu_142_p1 <= ap_const_lv22_2646(15 - 1 downto 0);

    grp_fu_148_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_148_ce <= ap_const_logic_1;
        else 
            grp_fu_148_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_148_p0 <= grp_fu_148_p00(8 - 1 downto 0);
    grp_fu_148_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rgb_V_2_reg_185),20));
    grp_fu_148_p1 <= ap_const_lv20_E98(13 - 1 downto 0);

    grp_fu_157_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_157_ce <= ap_const_logic_1;
        else 
            grp_fu_157_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_157_p0 <= grp_fu_157_p00(8 - 1 downto 0);
    grp_fu_157_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rgb_V_1_reg_180_pp0_iter2_reg),23));
    grp_fu_157_p1 <= ap_const_lv23_4B23(16 - 1 downto 0);
    grp_fu_157_p2 <= grp_fu_157_p20(22 - 1 downto 0);
    grp_fu_157_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_148_p3),23));
    icmp_ln37_fu_95_p2 <= "1" when (indvar_flatten_reg_78 = ap_const_lv21_1FA400) else "0";

    img_gray_src_4221_blk_n_assign_proc : process(img_gray_src_4221_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter6, icmp_ln37_reg_166_pp0_iter5_reg)
    begin
        if (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            img_gray_src_4221_blk_n <= img_gray_src_4221_full_n;
        else 
            img_gray_src_4221_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_gray_src_4221_din <= grp_fu_157_p3(22 downto 15);

    img_gray_src_4221_write_assign_proc : process(ap_enable_reg_pp0_iter6, icmp_ln37_reg_166_pp0_iter5_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_gray_src_4221_write <= ap_const_logic_1;
        else 
            img_gray_src_4221_write <= ap_const_logic_0;
        end if; 
    end process;


    img_in_4217_blk_n_assign_proc : process(img_in_4217_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln37_reg_166)
    begin
        if (((icmp_ln37_reg_166 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_in_4217_blk_n <= img_in_4217_empty_n;
        else 
            img_in_4217_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_in_4217_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln37_reg_166, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln37_reg_166 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_in_4217_read <= ap_const_logic_1;
        else 
            img_in_4217_read <= ap_const_logic_0;
        end if; 
    end process;


    img_rgb_src_4219_blk_n_assign_proc : process(img_rgb_src_4219_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter6, icmp_ln37_reg_166_pp0_iter5_reg)
    begin
        if (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            img_rgb_src_4219_blk_n <= img_rgb_src_4219_full_n;
        else 
            img_rgb_src_4219_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_rgb_src_4219_din <= tmp_V_reg_175_pp0_iter5_reg;

    img_rgb_src_4219_write_assign_proc : process(ap_enable_reg_pp0_iter6, icmp_ln37_reg_166_pp0_iter5_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln37_reg_166_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_rgb_src_4219_write <= ap_const_logic_1;
        else 
            img_rgb_src_4219_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
