// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module detectCorner_xfrgb2gray_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_in_4217_dout,
        img_in_4217_empty_n,
        img_in_4217_read,
        img_gray_src_4221_din,
        img_gray_src_4221_full_n,
        img_gray_src_4221_write,
        img_rgb_src_4219_din,
        img_rgb_src_4219_full_n,
        img_rgb_src_4219_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state9 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] img_in_4217_dout;
input   img_in_4217_empty_n;
output   img_in_4217_read;
output  [7:0] img_gray_src_4221_din;
input   img_gray_src_4221_full_n;
output   img_gray_src_4221_write;
output  [23:0] img_rgb_src_4219_din;
input   img_rgb_src_4219_full_n;
output   img_rgb_src_4219_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_in_4217_read;
reg img_gray_src_4221_write;
reg img_rgb_src_4219_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_in_4217_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln37_reg_166;
reg    img_gray_src_4221_blk_n;
reg    ap_enable_reg_pp0_iter6;
reg   [0:0] icmp_ln37_reg_166_pp0_iter5_reg;
reg    img_rgb_src_4219_blk_n;
reg   [20:0] indvar_flatten_reg_78;
wire   [0:0] icmp_ln37_fu_95_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_state8_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln37_reg_166_pp0_iter1_reg;
reg   [0:0] icmp_ln37_reg_166_pp0_iter2_reg;
reg   [0:0] icmp_ln37_reg_166_pp0_iter3_reg;
reg   [0:0] icmp_ln37_reg_166_pp0_iter4_reg;
wire   [20:0] add_ln37_fu_101_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [23:0] tmp_V_reg_175;
reg   [23:0] tmp_V_reg_175_pp0_iter2_reg;
reg   [23:0] tmp_V_reg_175_pp0_iter3_reg;
reg   [23:0] tmp_V_reg_175_pp0_iter4_reg;
reg   [23:0] tmp_V_reg_175_pp0_iter5_reg;
reg   [7:0] rgb_V_1_reg_180;
reg   [7:0] rgb_V_1_reg_180_pp0_iter2_reg;
reg   [7:0] rgb_V_2_reg_185;
wire   [21:0] grp_fu_142_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
wire    call_ret_ExtractPixel_fu_89_ap_ready;
wire   [7:0] call_ret_ExtractPixel_fu_89_ap_return_0;
wire   [7:0] call_ret_ExtractPixel_fu_89_ap_return_1;
wire   [7:0] call_ret_ExtractPixel_fu_89_ap_return_2;
reg    ap_block_pp0_stage0_01001;
wire   [21:0] grp_fu_148_p3;
wire   [22:0] grp_fu_157_p3;
wire   [7:0] grp_fu_142_p0;
wire   [14:0] grp_fu_142_p1;
wire   [7:0] grp_fu_148_p0;
wire   [12:0] grp_fu_148_p1;
wire   [7:0] grp_fu_157_p0;
wire   [15:0] grp_fu_157_p1;
wire   [21:0] grp_fu_157_p2;
reg    grp_fu_142_ce;
reg    grp_fu_148_ce;
reg    grp_fu_157_ce;
wire    ap_CS_fsm_state9;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [21:0] grp_fu_142_p00;
wire   [19:0] grp_fu_148_p00;
wire   [22:0] grp_fu_157_p00;
wire   [22:0] grp_fu_157_p20;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

detectCorner_ExtractPixel call_ret_ExtractPixel_fu_89(
    .ap_ready(call_ret_ExtractPixel_fu_89_ap_ready),
    .src_read(img_in_4217_dout),
    .ap_return_0(call_ret_ExtractPixel_fu_89_ap_return_0),
    .ap_return_1(call_ret_ExtractPixel_fu_89_ap_return_1),
    .ap_return_2(call_ret_ExtractPixel_fu_89_ap_return_2)
);

detectCorner_mul_mul_8ns_15ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 22 ))
mul_mul_8ns_15ns_22_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_142_p0),
    .din1(grp_fu_142_p1),
    .ce(grp_fu_142_ce),
    .dout(grp_fu_142_p2)
);

detectCorner_mac_muladd_8ns_13ns_22ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8ns_13ns_22ns_22_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_148_p0),
    .din1(grp_fu_148_p1),
    .din2(grp_fu_142_p2),
    .ce(grp_fu_148_ce),
    .dout(grp_fu_148_p3)
);

detectCorner_mac_muladd_8ns_16ns_22ns_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_8ns_16ns_22ns_23_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_157_p0),
    .din1(grp_fu_157_p1),
    .din2(grp_fu_157_p2),
    .ce(grp_fu_157_ce),
    .dout(grp_fu_157_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_fu_95_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_78 <= add_ln37_fu_101_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_78 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln37_reg_166 <= icmp_ln37_fu_95_p2;
        icmp_ln37_reg_166_pp0_iter1_reg <= icmp_ln37_reg_166;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln37_reg_166_pp0_iter2_reg <= icmp_ln37_reg_166_pp0_iter1_reg;
        icmp_ln37_reg_166_pp0_iter3_reg <= icmp_ln37_reg_166_pp0_iter2_reg;
        icmp_ln37_reg_166_pp0_iter4_reg <= icmp_ln37_reg_166_pp0_iter3_reg;
        icmp_ln37_reg_166_pp0_iter5_reg <= icmp_ln37_reg_166_pp0_iter4_reg;
        rgb_V_1_reg_180_pp0_iter2_reg <= rgb_V_1_reg_180;
        tmp_V_reg_175_pp0_iter2_reg <= tmp_V_reg_175;
        tmp_V_reg_175_pp0_iter3_reg <= tmp_V_reg_175_pp0_iter2_reg;
        tmp_V_reg_175_pp0_iter4_reg <= tmp_V_reg_175_pp0_iter3_reg;
        tmp_V_reg_175_pp0_iter5_reg <= tmp_V_reg_175_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_166 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rgb_V_1_reg_180 <= call_ret_ExtractPixel_fu_89_ap_return_1;
        rgb_V_2_reg_185 <= call_ret_ExtractPixel_fu_89_ap_return_2;
        tmp_V_reg_175 <= img_in_4217_dout;
    end
end

always @ (*) begin
    if ((icmp_ln37_fu_95_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_142_ce = 1'b1;
    end else begin
        grp_fu_142_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_148_ce = 1'b1;
    end else begin
        grp_fu_148_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_157_ce = 1'b1;
    end else begin
        grp_fu_157_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_gray_src_4221_blk_n = img_gray_src_4221_full_n;
    end else begin
        img_gray_src_4221_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_gray_src_4221_write = 1'b1;
    end else begin
        img_gray_src_4221_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_166 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_in_4217_blk_n = img_in_4217_empty_n;
    end else begin
        img_in_4217_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_166 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_in_4217_read = 1'b1;
    end else begin
        img_in_4217_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_rgb_src_4219_blk_n = img_rgb_src_4219_full_n;
    end else begin
        img_rgb_src_4219_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_rgb_src_4219_write = 1'b1;
    end else begin
        img_rgb_src_4219_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_fu_95_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_fu_95_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_fu_101_p2 = (indvar_flatten_reg_78 + 21'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_rgb_src_4219_full_n == 1'b0)) | ((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_gray_src_4221_full_n == 1'b0)))) | ((icmp_ln37_reg_166 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_in_4217_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_rgb_src_4219_full_n == 1'b0)) | ((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_gray_src_4221_full_n == 1'b0)))) | ((icmp_ln37_reg_166 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_in_4217_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_rgb_src_4219_full_n == 1'b0)) | ((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_gray_src_4221_full_n == 1'b0)))) | ((icmp_ln37_reg_166 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_in_4217_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln37_reg_166 == 1'd0) & (img_in_4217_empty_n == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter6 = (((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_rgb_src_4219_full_n == 1'b0)) | ((icmp_ln37_reg_166_pp0_iter5_reg == 1'd0) & (img_gray_src_4221_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_fu_142_p0 = grp_fu_142_p00;

assign grp_fu_142_p00 = call_ret_ExtractPixel_fu_89_ap_return_0;

assign grp_fu_142_p1 = 22'd9798;

assign grp_fu_148_p0 = grp_fu_148_p00;

assign grp_fu_148_p00 = rgb_V_2_reg_185;

assign grp_fu_148_p1 = 20'd3736;

assign grp_fu_157_p0 = grp_fu_157_p00;

assign grp_fu_157_p00 = rgb_V_1_reg_180_pp0_iter2_reg;

assign grp_fu_157_p1 = 23'd19235;

assign grp_fu_157_p2 = grp_fu_157_p20;

assign grp_fu_157_p20 = grp_fu_148_p3;

assign icmp_ln37_fu_95_p2 = ((indvar_flatten_reg_78 == 21'd2073600) ? 1'b1 : 1'b0);

assign img_gray_src_4221_din = {{grp_fu_157_p3[22:15]}};

assign img_rgb_src_4219_din = tmp_V_reg_175_pp0_iter5_reg;

endmodule //detectCorner_xfrgb2gray_1080_1920_s
